sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: QCf76lYwkzQskG06R2m7N/9HwA7qj+F3y1JmmO6xEOP2WhUs+d8/4JFVkBIwDVidQgnwY+0CaIPGir47gvPz5YwYeMHiD2zKLRcCDdU9bfsvFiyXlReIRzEOI+vZB+5uO+hv4j1PSpYmkJxB/1u11XI4xLpmCC/K0/ecX9GaBsba63J0wi0ub7qXGKA/Z8opghakKvufQVSZ50FuK/uhCm7QTt8BYbjCj7WhxYeIRrhh2Jxo0wmtn8uMzakvdt2NwwIz7198OtXdApn8u0tPUVpU9z6CBFzky0x30Jjlm5uTXDrWA7mCd3gn+rSpuTkJ425DMY7FRwneNI0P1CL/WwWLy+Hi+BCQoy3EUyOdKmG9uR5SBPnZS+gBJLwydT4Y2as+i0QDDFCQVc4vmowFpWz4NcVUTt2aUlRkz5dHMiO7SJXCh9oVt9XH1EeNC0MtQdlOpS1cbPdUH5doo8exvfVCTjBfmtbX15usgQg4A/4iYdPvDhLqc3gDJ7TQ1J9IEdM59ZHgh2YS+a1HQnBZhVioLD5nRenehDjYWvmnsjQoc+UxsKZ+5yEdmOC/8pnRGX+fAIMAowC6xR/SvRaOJ0tMIak3Lpjyp25ieQltt6nzKUtomJRG3wIHUx62ZIkmQKj0HuH6klc6VFcFJuOgO+Y/x3MwkHpXST75d+CcFtI=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: gJtCXmDDvVeByglvazkn+jI8Bdacz3ILSgaXLABY23Cc+PBplZU8ns0bEZSWMxyOSPYcyCIw/FlB763PGlUYfiXMXy/XtM2mjBpp1mtsT0sNEfyvf6pOfjYib+SjEDpRfAd88NiTqnspskGAIPinBYpPRJXI1g6N8m0chDzJoFScefCVNHAlw/Q0s2fQHSWcfdUijVWy80lNUpXdiAWwTSR32i9SlNeZdvetH/MF/N2ZKW1TlPdCNPpSOE+3yW+WurFe51/vcPzdmE+yRdmwbpjV2+cO3jgxLfl1JoTnv97vsAqUoQ7AJBq2dA7KwQa/o0WqpZT95K9LsrHK7lYRsmk18Hm6hJRvWHBgt2pJ4ZvMHzMH66SWZundXJ2LJa36mb40y/Lrs34fC5s7e05PpSKCM30pOKfasuSJGmWlt7/Dr8B1U/5Q/dPmLyfqo/bl6Mi8cp5+P8mH6x5XGfsTqzxYIyO7uoDJOkoFR2fbgyn1QJ+BEQymWwDJFIUvytlCkq1ctEkFk/9bJMMjPlgLF9JJpudp3MU9NnnoVMIl5brXQS2ZmCjbeYRXG1aY5UKD2o4in3TyLcoE/R+4f/bXCCAQ+QBKiEoHxfh3GONIOprBlgybTPyjtYwgz1N/4az3hhAz6EtudpFgVWW4eKDveWxa2+dM4YGDIn1znwsd2cA=
